# Generated by Django 6.0.6 on 2026-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
